### ISSUE TITLE
uWu pwetttty pweeease updateyyy ≧◡≦

### ISSUE THREAD

**Issue by plasma-node** [ReturnedTrue/gorp-ts#2]
(づ｡◕‿‿◕｡)づ (✿◠‿◠)

**Comment by ReturnedTrue** [comment]
(^・ω・^ ) I'm pretty busy atm, I'll update when I can but that might be a few weeks.  \\(￣︶￣*\\))

**Comment by howmanysmall** [comment]
![image](https://github.com/ReturnedTrue/gorp-ts/assets/26746527/34cca8ae-32a5-470d-9342-1041839b31ba)

**Comment by plasma-node** [comment]
(◕︿◕✿)  any uwpdate ? 

![image](https://github.com/ReturnedTrue/gorp-ts/assets/19627847/2b9a9ff5-09c8-432b-ac45-876cf2124446)

**Comment by ReturnedTrue** [comment]
Possibly next week I'll be free to update :3 (*￣3￣)╭

**Comment by ReturnedTrue** [comment]
Should be updated :O Let me know if there's any issues!
